const productsList = [
  "standart-business-cards",
  "stamping-business-cards",
  "stickers",
  "staple-brochures",
  "spring-brochures",
  "booklets",
  "silk-business-cards",
  "plastic-business-cards",
  "kashi-business-cards",
  "emboss-business-cards",
  "deboss-business-cards",
  "thermo-business-cards",
  "premium-business-cards",
  "certificates",
  "stickerbooks",
  "stickerpacks",
  "flyers",
  "envelops-standart",
  "envelops-premium",
  "standart-invitation-cards",
  "premium-invitation-cards",
  "books",
  "tags",
  "blanks",
  "hengers",
  "notepads",
  "folders",
  "drawings",
  "posters",
  "banners",
  "holst",
  "wall-calendars",
  "quarterly-calendars",
  "desktop-calendars",
  "photo",
  "id-photo",
  "diploms",
  "batteryboxes",
  "menu",
  "rollup",
  "spider",
  // "envelops-craft",
  "tshirt",
  // "packets-banana",
  // "cup",
];

export default productsList;
